# Generated by Django 4.2.6 on 2023-10-12 22:17
# Generated by Django 4.2.6 on 2023-10-12 22:17
from django.db import migrations

def cargar_registros_iniciales(apps, schema_editor):
    Customer = apps.get_model('store', 'Customer')
    Product = apps.get_model('store', 'Product')
    Order = apps.get_model('store', 'Order')
    OrderItem = apps.get_model('store', 'OrderItem')
    ShippingAddress = apps.get_model('store', 'ShippingAddress')

    product = Product.objects.create(name='Producto de Prueba', price=19.99, digital=False, image='LED_Mirror.jpg')


class Migration(migrations.Migration):
    dependencies = [
        ('store', '0002_alter_product_price'),
    ]

    operations = [
        migrations.RunPython(cargar_registros_iniciales),
    ]
