# Generated by Django 4.2.6 on 2023-10-13 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_imagenproducto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagenproducto',
            old_name='URLImagen',
            new_name='Imagen',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='ImagenPrincipal',
        ),
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='Color',
            field=models.CharField(default='Blanco', max_length=15),
        ),
        migrations.AddField(
            model_name='product',
            name='Descripcion',
            field=models.CharField(default='Sin descripción disponible', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='Destino',
            field=models.CharField(default='No especificado', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='Disponible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='Genero',
            field=models.CharField(default='Unisex', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='Material',
            field=models.CharField(default='No especificado', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='Precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='PuntosC',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='Talla',
            field=models.CharField(default='Talla Única', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='Tipo',
            field=models.CharField(default='No especificado', max_length=30),
        ),
    ]
