# Generated by Django 4.2.6 on 2023-10-24 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20231014_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonacionRopa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donante', models.CharField(help_text='Nombre del donante', max_length=100)),
                ('fecha_donacion', models.DateField(help_text='Fecha de la donación')),
                ('descripcion', models.TextField(help_text='Descripción de la donación')),
                ('cantidad', models.PositiveIntegerField(help_text='Cantidad de ropa donada')),
                ('tipo_ropa', models.CharField(help_text='Tipo de ropa donada', max_length=50)),
                ('talla', models.CharField(help_text='Talla de la ropa', max_length=10)),
                ('estado', models.CharField(help_text='Estado de la ropa', max_length=20)),
                ('puntuacion', models.DecimalField(decimal_places=2, help_text='Puntuación de la donación', max_digits=3)),
            ],
        ),
    ]
