# Generated by Django 4.2.6 on 2023-10-26 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_donacionropa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donacionropa',
            name='donante',
        ),
        migrations.AddField(
            model_name='donacionropa',
            name='Donante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customer'),
        ),
    ]
