# Generated by Django 4.2.6 on 2023-10-26 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_order_transaction_id'),
        ('store', '0009_remove_donacionropa_donante_donacionropa_donante'),
    ]

    operations = [
    ]
